// Generates the geometry used by the 3D globe:
//  - public/data/states.json : simplified US state polygons (lon/lat)
//  - public/data/dots.json   : land dots for the rest of the world
//  - app/data/generated/neighbors.ts : land borders between states
// Run with: node scripts/build-geo.mjs
import { readFileSync, writeFileSync } from 'node:fs'
import { feature, neighbors } from 'topojson-client'
import { geoContains, geoBounds } from 'd3-geo'

const FIPS = {
  '01': 'al', '02': 'ak', '04': 'az', '05': 'ar', '06': 'ca', '08': 'co', '09': 'ct',
  '10': 'de', '11': 'dc', '12': 'fl', '13': 'ga', '15': 'hi', '16': 'id', '17': 'il',
  '18': 'in', '19': 'ia', '20': 'ks', '21': 'ky', '22': 'la', '23': 'me', '24': 'md',
  '25': 'ma', '26': 'mi', '27': 'mn', '28': 'ms', '29': 'mo', '30': 'mt', '31': 'ne',
  '32': 'nv', '33': 'nh', '34': 'nj', '35': 'nm', '36': 'ny', '37': 'nc', '38': 'nd',
  '39': 'oh', '40': 'ok', '41': 'or', '42': 'pa', '44': 'ri', '45': 'sc', '46': 'sd',
  '47': 'tn', '48': 'tx', '49': 'ut', '50': 'vt', '51': 'va', '53': 'wa', '54': 'wv',
  '55': 'wi', '56': 'wy',
}

const read = (p) => JSON.parse(readFileSync(new URL(`../node_modules/${p}`, import.meta.url)))
const round = (n) => Math.round(n * 1000) / 1000

// --- States ---------------------------------------------------------------
const us = read('us-atlas/states-10m.json')
const geoms = us.objects.states.geometries
const keep = geoms.map((g) => g.id in FIPS)
const states = feature(us, us.objects.states).features.filter((f) => f.id in FIPS)

const toPolys = (geom) =>
  (geom.type === 'Polygon' ? [geom.coordinates] : geom.coordinates).map((poly) =>
    poly.map((ring) => ring.map(([x, y]) => [round(x), round(y)])),
  )

const out = states.map((f) => {
  let polys = toPolys(f.geometry)
  // Drop specks (tiny islands) except for small states where every island matters
  const area = (ring) => {
    let a = 0
    for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) a += (ring[j][0] + ring[i][0]) * (ring[j][1] - ring[i][1])
    return Math.abs(a / 2)
  }
  const max = Math.max(...polys.map((p) => area(p[0])))
  polys = polys.filter((p) => area(p[0]) > max * 0.002 && p[0].length > 3)
  // Alaska's Aleutians cross the antimeridian: keep the western part only
  if (f.id === '02') polys = polys.filter((p) => p[0].every(([x]) => x < 0))
  return { id: FIPS[f.id], polygons: polys }
})
writeFileSync('public/data/states.json', JSON.stringify(out))

// --- Neighbors ------------------------------------------------------------
const nb = neighbors(geoms)
const neighborMap = {}
geoms.forEach((g, i) => {
  if (!keep[i]) return
  neighborMap[FIPS[g.id]] = nb[i].filter((j) => keep[j]).map((j) => FIPS[geoms[j].id]).sort()
})
writeFileSync(
  'app/data/generated/neighbors.ts',
  `// Generated by scripts/build-geo.mjs — do not edit\nexport const neighbors: Record<string, string[]> = ${JSON.stringify(neighborMap, null, 2)}\n`,
)

// --- Land dots (slow: a few minutes, skip with SKIP_DOTS=1) ---------------
function buildDots() {
  const world = read('world-atlas/land-50m.json')
  const land = feature(world, world.objects.land)
  const usFeatures = states.map((f) => ({ f, b: geoBounds(f) }))
  const N = 90000
  const dots = []
  const golden = Math.PI * (3 - Math.sqrt(5))
  for (let i = 0; i < N; i++) {
    const y = 1 - (i / (N - 1)) * 2
    const lat = (Math.asin(y) * 180) / Math.PI
    const lon = ((((i * golden) % (2 * Math.PI)) * 180) / Math.PI) - 180
    if (lat < -60) continue // skip Antarctica
    const p = [lon, lat]
    if (!geoContains(land, p)) continue
    const inUS = usFeatures.some(({ f, b }) => {
      const [[x0, y0], [x1, y1]] = b
      return lat >= y0 && lat <= y1 && (x0 <= x1 ? lon >= x0 && lon <= x1 : true) && geoContains(f, p)
    })
    if (inUS) continue
    dots.push(Math.round(lat * 100) / 100, Math.round(lon * 100) / 100)
  }
  writeFileSync('public/data/dots.json', JSON.stringify(dots))
}
if (!process.env.SKIP_DOTS) buildDots()
console.log(`states: ${out.length}`)
